### PR TITLE
Incorporating mobileSAMv2

### PR DESCRIPTION
**Pull request by ian-coccimiglio**
Major features:
- Integrated the fast mobileSAMv2 model
- Scroll-wheel label shuffling
- Automatic downloading of weights via Google drive.
- Implemented independent bounding box and segmentation functions

Current regressions:
- I temporarily disabled Predicted IOU and Stability score metrics, as these were not directly exported from the mobileSAMv2 package.

Next goals:
- Develop a coherent UI
- Fix the Predicted IOU and Stability scores

Notes:
- Tox passed

### CODE REVIEW

**Comment by ian-coccimiglio** [comment]
Note, the changes to the README file should be reverted when merging

**Comment by bnorthan** [comment]
Just tested it and got it running.   There were a couple of installation steps I needed to do

1.  PIP install opencv-python, timm, torchpack, onxx, onxxsim should those be added as dependencies? 

2. Get Prompt_guided_Mask_Decoder.pt from [here]( https://github.com/ChaoningZhang/MobileSAM/tree/master/MobileSAMv2/PromptGuidedDecoder).  Is this something that should be downloaded, or because it is in the git repo of the vendored code we need to include it in our repo?

**Comment by ian-coccimiglio** [comment]
1) Yes, I needed to explicitly install timm and torchpack for it to work. I'm surprised the other packages needed explicit installation, but I suppose they do.

2) Whoops, I had changed the .gitignore to remove .pt/.pth files from version control because I didn't want to have the 200mb+ weight files explicitly in the repo. I think Prompt_guided_Mask_Decoder.pt should be in the repo itself, and the changes to the .gitignore reverted. The other two weights (ObjectAwareModel and EfficientVitL2) are downloaded from a googledrive to the /.cache/tnia-sam directory because they're large.

**Comment by bnorthan** [comment]
OK Great.  I can add dependencies and fix the .gitignore on my end.   I think there is a way to ignore all files of a type with exceptions for individual files of that type that you want.

**Pull request merged**
